# Supabase Configuration for ECOMMIND
project_id = "elpffiuadqkkkpiabmpm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3002"
additional_redirect_urls = ["https://www.ecommind.com.br"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true

[inbucket]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.image_transformation]
enabled = true

[analytics]
enabled = false



[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[experimental]
orioledb_version = ""
